- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.html
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23545" title="SB-23545" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23545</a>  Take video player on mobile prod
</td></table>
<br />
> Issue #SB-23545 fix: added next contet feature in video player

- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/sunbird-video-player.module.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23545" title="SB-23545" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23545</a>  Take video player on mobile prod
</td></table>
<br />
> Issue #SB-23545 fix: exported sunbird sdk from video player

- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.html
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.ts
- src/app/app.component.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24266" title="SB-24266" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24266</a>  Question Set : The "replay" and "exit" options are not properly aligned in the summary page
</td></table>
<br />
> Issue #SB-24266 fix: handled exit button and updated sdk version

- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24326" title="SB-24326" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10303&avatarType=issuetype" />SB-24326</a>  Mobile app: Menu & Exit option is not available on end screen for pdf and epub content
</td></table>
<br />
> Issue #SB-24326 fix: updated sdk version

- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.html
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23430" title="SB-23430" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23430</a>  Media/mime type compatibility on preview at creation side 
</td></table>
<br />
> Issue #SB-23430 fix: error events

- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/sunbird-video-player.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23430" title="SB-23430" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23430</a>  Media/mime type compatibility on preview at creation side 
</td></table>
<br />
> Issue #SB-23430 fix: added object in error event

- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-23430" title="SB-23430" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-23430</a>  Media/mime type compatibility on preview at creation side 
</td></table>
<br />
> Issue #SB-23430 fix: updated sdk version

- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/sunbird-video-player.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25138" title="SB-25138" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25138</a>  [Telemetry] context_env: "contentplayer" cdata should have {type: "PlayerVersion", id: "2.0"}
</td></table>
<br />
> Issue #SB-25138 fix: changed env to lowercase and added player version in cdata

- package-lock.json
- package.json
- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25129" title="SB-25129" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-25129</a>  ERROR event are not getting generated in staging environment
</td></table>
<br />
> Issue #SB-25129 fix: Video player not raising error event on internet disconnection

- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-24892" title="SB-24892" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10304&avatarType=issuetype" />SB-24892</a>  Downloaded video content is not getting played in new player
</td></table>
<br />
> Issue #SB-24892 fix: Offline player fix

- angular.json
- package-lock.json
- package.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25711" title="SB-25711" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25711</a>  Spike: Adaptive bit rate (Video Player)
</td></table>
<br />
> Issue #SB-25711 feat:  Added quality change functionality

- package-lock.json
- package.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25711" title="SB-25711" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10315&avatarType=issuetype" />SB-25711</a>  Spike: Adaptive bit rate (Video Player)
</td></table>
<br />
> Issue #SB-25711 feat: Added options to show quality selector menu on mobile devices

- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.html
- src/app/question-cursor-implementation.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25752" title="SB-25752" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-25752</a>  Displaying Accuracy Score in the Interactive Video Consumption Interface
</td></table>
<br />
Added total Score in final result JIRA key-> SB-25752
>  Added total Score in final result JIRA key-> SB-25752

- package-lock.json
- package.json
- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25752" title="SB-25752" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-25752</a>  Displaying Accuracy Score in the Interactive Video Consumption Interface
</td></table>
<br />
Qml updates JIRA key-> SB-25752
> Qml updates JIRA key-> SB-25752

- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25752" title="SB-25752" target="_blank"><img alt="Enhancement" src="https://project-sunbird.atlassian.net/secure/viewavatar?size=medium&avatarId=10311&avatarType=issuetype" />SB-25752</a>  Displaying Accuracy Score in the Interactive Video Consumption Interface
</td></table>
<br />
Removed JSON Parse from getMarkers() method
> Added total Score in final result JIRA key-> SB-25752

- package-lock.json
- package.json
- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.html
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.ts
…deo-player into release-4.5.0
> Issue #SB-0000 fix: Raising end event only once and fixed totalDuration

- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-25705" title="SB-25705" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-25705</a>  Automate the process of npm publish for sb-forms, common-components
</td></table>
<br /> …
> Issue #SB-25705 chore: Updated package

- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.spec.ts
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26905" title="SB-26905" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-26905</a>  Transcripts for player (video/audio) [Content player] V2
</td></table>
<br />
* Hardware …
> #SB-26905 feat: Transcripts for player (video/audio) [Content player] V2

- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26905" title="SB-26905" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-26905</a>  Transcripts for player (video/audio) [Content player] V2
</td></table>
<br />
* Hardware …
> #SB-26905 feat: Updated package version

- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.html
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- src/app/data.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26905" title="SB-26905" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-26905</a>  Transcripts for player (video/audio) [Content player] V2
</td></table>
<br />
* Hardware …
> #SB-26905 fix: Transcripts for player (video/audio) [Content player] V2

- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-26905" title="SB-26905" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-26905</a>  Transcripts for player (video/audio) [Content player] V2
</td></table>
<br />
* Hardware …
> #SB-26905 chore: updated player version

- README.md
- angular.json
- package-lock.json
- package.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.ts
- projects/sunbird-video-player/src/public-api.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/app/data.ts
- src/app/question-cursor-implementation.service.ts
- src/app/services/api.service.ts
- src/environments/environment.ts
> Removed hardcoded API response and using dynamic content id to render video content

- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
- src/app/data.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-30185" title="SB-30185" target="_blank"><img alt="Defect" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10304?size=medium" />SB-30185</a>  Transcript state is not restored when user replays the video content
</td></table>
<br />
* Software …
> #SB-30185 fix: Transcript state is not restored when user replays the video content

- README.md
- projects/sunbird-video-player/README.md
- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-30411" title="SB-30411" target="_blank"><img alt="Task" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10318?size=medium" />SB-30411</a>  Transcripts feature documentation for microsite
</td></table>
<br />
> #SB-30411 chore: Transcripts feature documentation for microsite

- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/services/viewer.service.spec.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.spec.data.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.spec.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.component.ts
- projects/sunbird-video-player/src/lib/sunbird-video-player.service.ts
> Issue #SB-30516 fix: Added telemetry for interactive player

- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.spec.ts
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
> Issue SB-30516 fix: Added code to get video duration

- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/services/viewer.service.spec.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/SB-30516" title="SB-30516" target="_blank"><img alt="Story" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10315?size=medium" />SB-30516</a>  Interactive Video - Online Playback
</td></table>
<br />
> Issue SB-30516 fix: Interception Points is an empty object

- README.md
- package-lock.json
- package.json
- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- schematics/collection.json
- schematics/ng-add/index.ts
- schematics/ng-add/messages.ts
- schematics/ng-add/schema.json
- schematics/ng-add/schema.ts
- schematics/ng-add/setup-project.ts
- schematics/ng-add/steps/add-spp-module.ts
- schematics/ng-add/steps/add-spp-style.ts
- schematics/utils/package-config.ts
- schematics/utils/project.ts
- tsconfig.schematics.json
Implementation video link:- 
part 1 :- https://drive.google.com/file/d/1tNdPHXoO0jTwnhjuYcGU1PHFOapuCCg2/view?usp=drivesdk
part 2 :- https://drive.google.com/file/d/12GbePLhqjmuLPrls7n6J4zqBJOalq2BB/view?usp=drivesdk
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-7" title="KN-7" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-7</a>  Sunbird-video-player: Publishing as NG module
</td></table>
<br />
[Issue #KN-7 feat: Publishing as NG module](https://github.com/project-sunbird/sunbird-video-player/commit/3a19a2c846706ecec401061754f489b901e2f5ac)
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. …
> Issue #KN-7 feat: Publishing as NG module

- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.spec.ts
- projects/sunbird-video-player/src/lib/services/viewer.service.ts
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-239" title="KN-239" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-239</a>  Implementation - Knowlg player app for PDF, Video and Epub player
</td></table>
<br />
* Hardware …
> Issue #KN-239 fix: Added questionCursor as  optional dependency

- angular.json
- package-lock.json
- package.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/test.ts
- projects/sunbird-video-player/tsconfig.lib.json
- projects/video-player-wc/src/environments/environment.ts
- projects/video-player-wc/src/polyfills.ts
- projects/video-player-wc/src/test.ts
- src/environments/environment.ts
- src/polyfills.ts
- src/test.ts
- tsconfig.json
- web-component/styles.css
Implementation Video : https://drive.google.com/file/d/1cjlgLx7QgRlvLqAYNC2fIDPKYHbNOO7R/view?usp=sharing
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-523" title="KN-523" target="_blank"><img alt="RFC" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10322?size=medium" />KN-523</a>  Video, Epub Players - Angular migration from version 9 to 12
</td></table>
<br />
Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any …
> Issue #KN-523 feat: Video Player: Angular migration from version  11 to 12

- projects/sunbird-video-player/package-lock.json
- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- web-component/assets/videojs-transcript-click.min.js
> Issue #KN-710 fix: video player end page streaming url fix

- projects/sunbird-video-player/package.json
- projects/sunbird-video-player/src/lib/components/video-player/video-player.component.ts
- web-component/sunbird-video-player.js
> Issue #KN-0000 merge: merged release-5.2.0 into release-5.3.0

- package.json
- projects/sunbird-video-player/package.json
<table>
<td>
<a href="https://project-sunbird.atlassian.net/browse/KN-733" title="KN-733" target="_blank"><img alt="Bug" src="https://project-sunbird.atlassian.net/rest/api/2/universal_avatar/view/type/issuetype/avatar/10303?size=medium" />KN-733</a>  CLONE - The course progress is not updating as completed after consuming the 20% of video content and close.
</td></table>
<br />
Issue #KN-733 feat: visited length issue fixed
> Issue #KN-733 feat: visited length issue fixed

- projects/sunbird-video-player/package.json
> Issue #KN-834 chore: updated package version

- README.md
- projects/sunbird-video-player/package.json
- web-component/package.json
> Issue #KN-834 feat: updated the document

- .github/workflows/publish_module.yml
- .github/workflows/publish_web_component.yml
- .github/workflows/pull_request.yml
- package-lock.json
- projects/sunbird-video-player/package-lock.json
> GitHub actions for pr
